project_id = "bclktrcbwpwsxksbhqsv"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.create-admin]
verify_jwt = false

[functions.send-post-notification]
verify_jwt = false